/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module vlsifinal(AROM, ENROM, D3ROM, D2ROM, D1ROM, D0ROM);
  wire [255:0] _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input [7:0] AROM;
  wire [7:0] AROM;
  output D0ROM;
  wire D0ROM;
  output D1ROM;
  wire D1ROM;
  output D2ROM;
  wire D2ROM;
  output D3ROM;
  wire D3ROM;
  input ENROM;
  wire ENROM;
  wire [255:0] wordlines;
  decode_8_256 in_decoder (
    .A(AROM),
    .EN(ENROM),
    .Q(_0_)
  );
  output_matrix outmatrix (
    .D0(_4_),
    .D1(_3_),
    .D2(_2_),
    .D3(_1_),
    .Q(wordlines)
  );
  assign wordlines = _0_;
  assign D3ROM = _1_;
  assign D2ROM = _2_;
  assign D1ROM = _3_;
  assign D0ROM = _4_;
endmodule
